Grid letrehozasa a Models mappaba.
skorom/NetPlayProject pull request #2
Opened 2019-10-13 05:45 UTC by Kristofy

Letrehoztam az amboba tablat.

2019-10-16 15:18 UTC, skorom commented on AIMoba/AIMoba/Models/GridModel.cs
> +            return true;
Ez mikor lesz implemetálva? Hadj itt egy TODO-t

2019-10-16 15:25 UTC, skorom requested changes
Tetszik a kód. Nincsen emergency kommentem, csak amolyan "design" kommentek, konvenciók, amiket jó követni.

2019-10-16 15:25 UTC, skorom commented on AIMoba/AIMoba/Models/GridModel.cs
> +            return true;
Ez mikor lesz implenetálva/melyik trello taskban? Hadj itt egy TODO-t

2019-10-16 15:25 UTC, skorom commented on AIMoba/AIMoba/Models/GridModel.cs
> +        public FieldState this[int iPos, int jPos]
Ez amúgy király, de mindenképpen legyen egy függvény is, ami adott pozira visszaadja ki van ott

2019-10-16 15:25 UTC, skorom commented on AIMoba/AIMoba/Models/GridModel.cs
> +        public void SetSize(int width, int height)
Ennek nem teljesen értem az értelmét. Mármint ha már egyszer van egy pálya, akkor menet közben lehet majd változtatni? Ha nem, akkor ne lehessen menet közben változtatni, hanem ha új pálya van, akkor új objektum jön vissza ebből az osztályból. Szerintem elég lenne egy konstruktor és jónapot.

2019-10-16 15:25 UTC, skorom commented on AIMoba/AIMoba/Models/GridModel.cs
> +    public enum FieldState
Tetszik az enum mátrixos megoldás. Kissé szokatlan, de működhet. Az viszont biztos, hogy nem raknám ebbe a file-ba, hiszen biztosan máshol is kell majd használni és gyakorlatilag ez nem ennek a része. Ennek az osztálynak persze szüksége van rá, de nem a része.

2019-10-17 19:55 UTC, Kristofy commented on AIMoba/AIMoba/Models/GridModel.cs
> +    public enum FieldState
Létrehoztam egy Data mappát és áttettem a Data/FieldState.cs -be.

2019-10-18 15:15 UTC, skorom requested changes
2 kommentemre nem érkezett válasz

2019-10-18 18:43 UTC, Kristofy commented on AIMoba/AIMoba/Models/GridModel.cs
> +            return true;
Implementáltam. Nincs sok szabály az amőba játékban, ezért nem láttam értelmét tovább váratni
.

2019-10-18 18:45 UTC, Kristofy commented on AIMoba/AIMoba/Models/GridModel.cs
> +        public FieldState this[int iPos, int jPos]
Létrehoztam egy ilyen függvényt, a neve GetFiledAtPosition.

2019-10-18 18:45 UTC, Kristofy commented on AIMoba/AIMoba/Models/GridModel.cs
> +            return true;
Implementáltam. Nincs sok szabály az amőba játékban, ezért nem láttam értelmét tovább váratni
.

2019-10-18 18:46 UTC, Kristofy commented on AIMoba/AIMoba/Models/GridModel.cs
> +        public FieldState this[int iPos, int jPos]
Létrehoztam egy ilyen függvényt, a neve GetFiledAtPosition.

2019-10-18 18:46 UTC, Kristofy commented on AIMoba/AIMoba/Models/GridModel.cs
> +        public void SetSize(int width, int height)
Ezt a függvényt töröltem, jobban belegondolva tényleg nincs értelme.

2019-10-19 13:05 UTC, tmskss approved these changes

2019-10-19 13:08 UTC, skorom approved these changes
Jónak tűnik nekem :) Köszi a javításokat

2019-10-20 15:09 UTC, ghost approved these changes

2019-10-20 16:10 UTC, merged