Weblap
skorom/NetPlayProject pull request #5
Opened 2019-10-19 18:45 UTC by berekmeri

Még kettő menü pont szabadon van hagyva

2019-10-19 20:00 UTC, skorom requested changes
Alapvetően 2 nagyon fontos kommentem lenne:
1. az oldal nem reszponzív. A menüt pedig így kellene megcsinálni (összefolynak a menü elemei)
2. Szerintem ennek nem az indexben a helye, legalább is a menünek, mert az valszeg minden oldalon ott lesz, vagyis a "_Layout.cshtml"-ben jobb lenne. Ezt át kellene gondolni. Azért adok most "request change"-t, hogy gondolkodj rajta, de ha az a döntés, hogy legyen itt, az is jó.

2019-10-22 08:30 UTC, berekmeri commented
A @Kristofy volt bejelentkezve Visual Studioban  GitHubbal ezért commitolt ő.

2019-10-23 21:56 UTC, skorom approved these changes
Nem nagyon értek a front-endhez, nem tudom megítélni, hogy ez a leghatékonyabb megoldás-e, de szerintem jól néz ki. Lehet hogy még lesz rajta változás, ahogy jönnek a feature-ök, de váznak jó lesz :)

2019-11-05 22:00 UTC, ghost approved these changes

2019-11-07 07:59 UTC, merged